# Generated by Django 5.0.7 on 2024-07-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver1', models.CharField(max_length=50)),
                ('driver2', models.CharField(max_length=50)),
                ('circuit', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
