# Generated by Django 5.0.7 on 2024-07-28 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselection',
            name='circuit',
        ),
        migrations.RemoveField(
            model_name='userselection',
            name='year',
        ),
    ]
