# Generated by Django 5.0.7 on 2024-07-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0002_remove_userselection_circuit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselection',
            name='year',
            field=models.PositiveIntegerField(default=2018),
        ),
    ]
