# Generated by Django 5.0.7 on 2024-08-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0004_userselection_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselection',
            name='session',
            field=models.CharField(default='', max_length=2),
        ),
    ]
