# Generated by Django 5.0.7 on 2024-12-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visualizations", "0005_userselection_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userselection",
            name="driver1",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="userselection",
            name="driver2",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="userselection",
            name="race",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userselection",
            name="session",
            field=models.CharField(max_length=2),
        ),
    ]
